# Generated by Django 3.1 on 2020-08-27 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offfer',
            new_name='Offer',
        ),
    ]
